// Run: npx wrangler dev --local --port 8788  (with .dev.vars containing EXPORT_KEY=test-export-key-123456)  then  node test/smoke.mjs
const BASE = process.env.BASE || "http://127.0.0.1:8788";
const KEY = process.env.EXPORT_KEY || "test-export-key-123456";
const OK = "https://thekitchenat22.com";
let pass = 0, fail = 0;
const t = (name, cond, extra = "") => { cond ? pass++ : fail++; console.log((cond ? "ok   " : "FAIL ") + name + (cond ? "" : "  " + extra)); };
const post = (id, body, origin = OK, ip) => fetch(`${BASE}/api/surveys/${id}`, { method: "POST", headers: { "Content-Type": "application/json", ...(origin ? { Origin: origin } : {}), ...(ip ? { "CF-Connecting-IP": ip } : {}) }, body: JSON.stringify(body) });

let r = await post("menu-2026-10", { lang: "es", src: "qr", menu: "Birria", delivery: "Sushi", roomservice: "Horarios más amplios", improve: "speed" });
t("valid submit → 204", r.status === 204, r.status);
t("CORS header echoes allowed origin", r.headers.get("access-control-allow-origin") === OK);
r = await post("menu-2026-10", { menu: "x" }, "https://evil.example");
t("disallowed origin → 403", r.status === 403, r.status);
r = await post("menu-2026-10", {});
t("empty → 400", r.status === 400, r.status);
r = await post("menu-2026-10", { improve: "hacked" });
t("invalid choice only → 400", r.status === 400, r.status);
r = await post("nope", { menu: "x" });
t("unknown survey → 404", r.status === 404, r.status);
r = await fetch(`${BASE}/api/surveys/menu-2026-10`, { method: "OPTIONS", headers: { Origin: OK } });
t("preflight → 204", r.status === 204, r.status);
await post("menu-2026-10", { lang: "en", src: "qr", menu: '=HYPERLINK("http://x")', delivery: 'He said "hi", ok', improve: "flavor" });
r = await fetch(`${BASE}/api/surveys/menu-2026-10/export.csv`);
t("export without key → 403", r.status === 403, r.status);
r = await fetch(`${BASE}/api/surveys/menu-2026-10/export.csv?key=wrong`);
t("export wrong key → 403", r.status === 403, r.status);
r = await fetch(`${BASE}/api/surveys/menu-2026-10/export.csv?key=${KEY}`);
const csv = await r.text();
t("export ok → 200 csv", r.status === 200 && /text\/csv/.test(r.headers.get("content-type")), r.status);
t("csv has header + 2 rows", csv.trim().split("\n").length >= 3, csv);
t("formula injection guarded", csv.includes(`"'=HYPERLINK`), csv);
t("quotes escaped", csv.includes('"He said ""hi"", ok"'), csv);
r = await fetch(`${BASE}/api/surveys/menu-2026-10/summary?key=${KEY}`);
const s = await r.json();
t("summary counts", s.total >= 2 && s.choices.mejora.speed >= 1 && s.choices.mejora.flavor >= 1, JSON.stringify(s));
t("no IP stored in export", !/\d+\.\d+\.\d+\.\d+/.test(csv));
let last;
for (let i = 0; i < 32; i++) last = await post("menu-2026-10", { menu: "spam " + i }, OK, "9.9.9.9");
t("rate limit → 429 after daily limit", last.status === 429, last.status);
r = await post("menu-2026-10", { menu: "other person" }, OK, "8.8.8.8");
t("different person unaffected", r.status === 204, r.status);
r = await fetch(`${BASE}/api/surveys/menu-2026-10/responses?key=${KEY}&confirm=yes`, { method: "DELETE" });
t("wipe needs no-key → 403", (await fetch(`${BASE}/api/surveys/menu-2026-10/responses?confirm=yes`, { method: "DELETE" })).status === 403);
t("wipe without confirm → 400", (await fetch(`${BASE}/api/surveys/menu-2026-10/responses?key=${KEY}`, { method: "DELETE" })).status === 400);
t("wipe ok", r.status === 200 && (await r.json()).deleted >= 2);
r = await fetch(`${BASE}/api/surveys/menu-2026-10/summary?key=${KEY}`);
t("summary empty after wipe", (await r.json()).total === 0);
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
